## numpy

#### 基本操作
- 配列の作り方
- 型について
- 2次元配列
- reshape, flatten
- shape, ndim, size

In [1]:
#　モジュールのインポート numpyを使うときは必ずこのコードをまず打つ
import numpy as np

In [2]:
# 配列を作成する
array = np.array([10, 20, 30, 40, 50])
print(array)

[10 20 30 40 50]


In [4]:
type([10,20,30,40,50])

list

In [3]:
type(np.array([10,20,30,40,50]))

numpy.ndarray

In [3]:
array = np.array((60, 70, 80, 90, 100))
print(array)

[ 60  70  80  90 100]


In [4]:
# 型は混在できない 型を統一してくれる　
array_1 = np.array([1, 1.5, 2, 3])  # int とfloat 
array_2 = np.array([1, 1.5, '2', 3]) # 文字列 と数値
array_3 = np.array([1, 1.5, True, False])  # 論理値と数値

print(array_1)
print(array_2)
print(array_3)

[1.  1.5 2.  3. ]
['1' '1.5' '2' '3']
[1.  1.5 1.  0. ]


In [5]:
# 多次元配列
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
# reshape(行,　列)
lis = [1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12]
array_0 = np.array(lis)
array_1 = np.array(lis).reshape(3,4)#4行3列
array_2 = np.array(lis).reshape(4,3)#3行4列
array_3 = np.array(lis).reshape(-1,4) # -1を指定すると自動的に計算される
array_4 = np.array(lis).reshape(4,-1)

print(array_0)
print()
print(array_1)
print()
print(array_2)
print()
print(array_3)
print()
print(array_4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
# 1次元配列に変換
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(array)
print()

array = array.flatten()
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# 配列が何行何列かを調べる
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(array)
print()
array.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]



(2, 5)

In [9]:
# 配列の次元を調べる
array.ndim

2

In [10]:
# 要素の数を調べる
array.size

10

#### 効率的な配列の作成
- arange
- ゼロ行列の作り方
- ランダム配列の作り方
- random.seed

In [11]:
# np.arange(開始, 終了, ステップ)
array = np.arange(10)
print(array)
print()

array = np.arange(1,10)
print(array)
print()

array = np.arange(1,10,2)
print(array)
print()

[0 1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]

[1 3 5 7 9]



In [12]:
# 零行列  
array = np.zeros(9)
print(array)  
print()

array = np.zeros((2,3))
print(array)  

[0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# 0-1の乱数を作成
array = np.random.rand(5)
print(array)
print()

array = np.random.rand(5)
print(array)
print()

array = np.random.rand(2, 5)
print(array)

[0.68222834 0.62173901 0.21059451 0.67456095 0.54791604]

[0.22726485 0.33043693 0.84597157 0.42806712 0.84426224]

[[0.71410191 0.09633714 0.81596844 0.35993168 0.72933131]
 [0.14339029 0.47674916 0.71078137 0.19667069 0.58799367]]


In [14]:
# 乱数を固定
np.random.seed(0)
array = np.random.rand(5)
print(array)
print()

np.random.seed(0)
array = np.random.rand(5)
print(array)
print()

np.random.seed(1234)
array = np.random.rand(5)
print(array)
print()

np.random.seed(1234)
array = np.random.rand(5)
print(array)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]


#### 要素の追加・参照
- append
- 参照（スライシング）
- for文

In [15]:
# 足し算をすると要素同士が足されて追加できない
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = array_1 + array_2
print(array_3)

[5 7 9]


In [16]:
# np.append
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.append(array_1, array_2)
print(array_3)


[1 2 3 4 5 6]


In [17]:
# 参照
array = np.arange(0, 90, 10).reshape(3,3)
print(array)
print()

print(array[0])
print()

print(array[0][1])
print()

print(array[0, 1])
print()

print(array[:, 1])
print()

print(array[-1, :])
print()

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]

[ 0 10 20]

10

10

[10 40 70]

[60 70 80]



In [18]:
# for文
array = np.arange(6).reshape(3,2)
print(array)
print()

for item in array:
    print(item)

print()
for item in array.flatten():
    print(item)

[[0 1]
 [2 3]
 [4 5]]

[0 1]
[2 3]
[4 5]

0
1
2
3
4
5


#### 演算
- 四則演算
- ブロードキャスト
- 内積

In [19]:
# 足し算
A = np.arange(0, 90, 10).reshape(3,3)
B = A + 10

print(A)
print()
print(B) # 全体の要素に反映される(ブロードキャスト)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [20]:
# 引き算
A = np.arange(0, 90, 10).reshape(3,3)
B = A - 10

print(A)
print()
print(B)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]

[[-10   0  10]
 [ 20  30  40]
 [ 50  60  70]]


In [21]:
# 掛け算
A = np.arange(0, 90, 10).reshape(3,3)
B = A * 3

print(A)
print()
print(B)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]

[[  0  30  60]
 [ 90 120 150]
 [180 210 240]]


In [22]:
# 割り算
A = np.arange(0, 90, 10).reshape(3,3)
B = A / 2

print(A)
print()
print(B) # float型になる

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]

[[ 0.  5. 10.]
 [15. 20. 25.]
 [30. 35. 40.]]


In [23]:
# 行列とベクトルの演算
A = np.arange(0, 90, 10).reshape(3,3)
B = np.arange(0, 30, 10).reshape(3,1)
C = A + B

print(A)
print()
print(B)
print()
print(C) # 足りない分が補間される(ブロードキャスト)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]

[[ 0]
 [10]
 [20]]

[[  0  10  20]
 [ 40  50  60]
 [ 80  90 100]]


In [24]:
# 行列と行列の演算  
A = np.arange(0, 90, 10).reshape(3,3)
B = np.arange(100, 190, 10).reshape(3,3)
C = A + B

print(A)
print()
print(B)
print()
print(C)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]

[[100 110 120]
 [130 140 150]
 [160 170 180]]

[[100 120 140]
 [160 180 200]
 [220 240 260]]


In [25]:
# 内積
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print()
print(B)
print()

AB = np.dot(A, B)
#AB = A.dot(B)

print(AB)
# [[1*5 + 2*7,  1*6 + 2*8],
#  [3*5 + 4*7,  3*6 + 4*8]]

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]


#### 行方向・列方向の処理
- axis

In [26]:
array = np.arange(6).reshape(2, 3)
print(array)
print()

# 全体への処理
print(np.sum(array))
print()

# 行方向の処理
print(np.sum(array, axis=0))
print()

# 列方向の処理
print(np.sum(array, axis=1))

[[0 1 2]
 [3 4 5]]

15

[3 5 7]

[ 3 12]
